---
- name: Deploy application from Git
  hosts: app_server
  become: yes
  tasks:
    - name: Clone Git repository
      git:
        repo: https://github.com/example/app.git
        dest: /path/to/app
        version: master